---
title: '*Diospyros* root DGE analysis'
output:
pdf_document: default
html_notebook: default
html_document:
df_print: paged
word_document: default
---
  
  Data generated by K. Emelianova et al., code adapted by T. Khastgir from https://bioconductor.org/packages/release/workflows/vignettes/RNAseq123/inst/doc/limmaWorkflow.html

```{r message=FALSE, warning=FALSE}
library(limma)
library(Glimma)
library(edgeR)
library(factoextra)
library(topGO)
setwd("C:/Users/Admin/Documents/rna")
```
---

Comparisons and Contrasts
---
```{r message=FALSE, warning=FALSE}

###Read and preprocess data
counts_raw <- read.csv("C:/Users/Admin/Documents/rna/rootRNAcounts_ordered", header = TRUE, sep = "\t")
counts <- DGEList(counts = counts_raw[,c(1,7:42)], group = as.factor(rep(c("sed","ult","sed","ult","sed", "ult"), rep.int(6,6))))
species <- as.factor(rep(c("cal","spn","imp","heq","lab","rev"), rep.int(6,6) ))
counts$samples$species <- species
group <- counts$samples$group    # make 'counts' dataframe specifying species and soil preferences

annotation <- read.csv("C:/Users/Admin/Documents/rna/amin_redo/vie1167c_OmicsboxAminGene_Fannotation.txt", sep = "\t")
annotation <- annotation[annotation$SeqName %in% counts$genes$Geneid,]
annotation <- annotation[,c("SeqName", "Description","Length","GO.Names","GO.IDs")]    #annotations of genes in counts table

###Filter & normalise
dim(counts)	#check initial number of genes
keep.exprs <- filterByExpr(counts, group=species)
counts <- counts[keep.exprs,, keep.lib.sizes=FALSE]    # 10/(median lib size) CPM cutoff met for at least 6 samples (size of a species group)
dim(counts)    #check final number of genes post-filtering
cpm <- cpm(counts)    #convert to counts per million
lcpm <- cpm(counts, log=TRUE)    #convert counts to log2(cpm)

###Checking if they need normalisation
mycolors <- c("#586085","#EA969C","#659794","#C9CCEA","#D65B5A","#F5C98E")
names(mycolors) <- levels(species)
boxplot(lcpm, las=2, col=mycolors[species], main="", cex.axis=0.75)

###MDS plot
plotMDS(lcpm, labels=colnames(lcpm), col=mycolors[species])

###PCA plot
lcpm.pca <- prcomp(t(lcpm), scale = TRUE)
fviz_eig(lcpm.pca)
fviz_pca_biplot(lcpm.pca, axes = c(1,2), habillage = species, geom = "text", col.var = "#99d88e", select.var = list(contrib = 10)) +
  scale_color_manual(values=mycolors)    #pca based on logCPM, showing the top 10 loadings (genes)

###Comparisons and Overlaps
design <- model.matrix(~0+species)    #comparisons are between species 
v <- voom(counts, design, plot=TRUE)    #voom plots mean log2cpm of counts across each species and the square root (why??) of the stddev within to assess heteroscedasticity
vfit <- lmFit(v, design)    # fit a linear model using weighted least squares for each gene

#ultramafic vs non-ultramafic contrasts
contrast.matrix <- makeContrasts(
  spnVScal = speciesspn - speciescal,
  heqVSimp = speciesheq - speciesimp,
  revVSlab = speciesrev - specieslab,
  levels = colnames(design))
contrast.matrix

vfit_contrast <- contrasts.fit(vfit, contrasts=contrast.matrix)    #Comparisons between groups are obtained as contrasts of the fitted linear models
efit_contrast <- eBayes(vfit_contrast)    #shrinks standard errors that are much larger or smaller than those from other genes towards the average standard error
efit_contrast
plotSA(efit_contrast, main="Final model: Mean-variance trend")    #Plot log residual
#standard deviation versus average log expression to assess heteroscedasticity
summary(decideTests(efit_contrast))
tfit_contrast <- treat(vfit_contrast, lfc=1.5)  #cutoff required to be listed as differentially expressed: adj.P-value < 0.05, log fold change >= 1.5
dt_contrast <- decideTests(tfit_contrast)
summary(dt_contrast)
de_contrast.common <- which(dt_contrast[,1]!=0 & dt_contrast[,2]!=0)
head(tfit_contrast$genes$SYMBOL[de_contrast.common])
vennDiagram(dt_contrast[,1:3],circle.col=c("grey","grey","grey"))

###Volcano plots
plotMD(tfit_contrast, column=1, status=dt_contrast[,1], main=colnames(tfit_contrast)[1],hl.col = c("#F5C98E","#586085"))
plotMD(tfit_contrast, column=2, status=dt_contrast[,2], main=colnames(tfit_contrast)[2],hl.col = c("#EA969C","#659794"))
plotMD(tfit_contrast, column=3, status=dt_contrast[,3], main=colnames(tfit_contrast)[3],hl.col = c("#D65B5A","#C9CCEA"))

###print gene lists columns of interest onto text file
tt_spncal <- topTreat(tfit_contrast, coef=1, number=Inf, sort.by="none")    #change coeff to 2 or 3 or heq-imp or rev-lab comparisons respectively
merged_spncal <- merge(tt_spncal, annotation, by.x = "Geneid", by.y = "SeqName", all.x = TRUE)
de_spncal <- merged_spncal[merged_spncal$adj.P.Val<0.05,]
de_spncal <- de_spncal[abs(de_spncal$logFC)>=1.5,]    #double-checking the P-value and log fold change thresholds
#de_spncal_totopgo <- de_spncal[,c("Geneid","GO.IDs",)]
#write.table(de_spncal$Geneid, file = "de_spncal_totopgo.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
```
